### ISSUE TITLE
Automatic header being created for tables in PDF

### ISSUE THREAD

**Issue by joshuaneedham** [surveyjs/survey-pdf#10]
If a table extended onto a new page it is automatically creating a header. If no header is present in table it automatically creates one. If there is a header and the table extends to a new page then another header is created. Please see screenshot example of a header upon display of the table which is correct, and the table on the second and third page. The example extends for two additional pages beyond the first.
I should point out that this is coming from a CKEditor field. It displays properly within the CKEditor code area but once in PDF is where the table issue occurs.
<img width="622" alt="Screen Shot 2020-03-27 at 10 18 56 AM" src="https://user-images.githubusercontent.com/63559/77771606-e44b0500-7014-11ea-8712-6137905a2bb5.png">
<img width="650" alt="Screen Shot 2020-03-27 at 10 19 08 AM" src="https://user-images.githubusercontent.com/63559/77771611-e4e39b80-7014-11ea-9f19-27dc8468c8dd.png">
<img width="632" alt="Screen Shot 2020-03-27 at 10 19 26 AM" src="https://user-images.githubusercontent.com/63559/77771613-e57c3200-7014-11ea-9f1a-2452c5ba4fab.png">

**Comment by gologames** [comment]
Hello,

Unfortunately, we don't understand your issue very clear. There are many potential issues with html in PDF. For this we add special image-like html rendering in PDF some time ago. SurveyPDF supports custom widget rendering, but so as CKEditor produce html then may be problems with render CKEditor in PDF. In any case, please, could you share as a SurveyJSON with the issue? So we can investigate it

Thanks, Alex
SurveyJS Team

**Comment by joshuaneedham** [comment]
Alex,
We are pasting very simple HTML without any styles into a CKEditor field. When we save the PDF all text looks fine(with exception to not allowing any styling in the PDF) and I have managed to get the tables looking good as well. The issue is the tables span more than just a single page. As you can see from the screenshots an additional header row is being inserted at the top of the table on subsequent pages.

The first image is the beginning of the table and looks great. The second image is a new page in the PDF which includes an additional header row, same with the third image which again is a new page with an additional header row being injected.

Let me know if this helps.

Joshua

**Comment by gologames** [comment]
Hello,

What do you mean by "simple HTML"? Unfortunately, tables is too complex for correct PDF render without image-like render. Could you please share us a SurveyJSON or work sample with the issue. So we can investigate it

Thanks, Alex
SurveyJS Team
