### ISSUE TITLE
Always use radiogroup for Boolean questions

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-pdf#121]
We have the `booleanRenderAs` property that specifies how to export Boolean questions and accepts the "default" and "radiogroup" values. "Default" gives strange results:

- undefined
     ![image](https://user-images.githubusercontent.com/18551316/167123402-7062af43-d793-4ea5-b894-20b06573b535.png)
- true:
    ![image](https://user-images.githubusercontent.com/18551316/167123588-c6039b1f-4f92-4f5f-a018-334d77b2e6cc.png)
- false:
    ![image](https://user-images.githubusercontent.com/18551316/167123525-bd184b19-3160-4d20-890a-75efd4487245.png)

I would expect to see something like this:
![image](https://user-images.githubusercontent.com/18551316/167123901-363a7ab7-6fdf-49c8-91c6-3c62a076ddad.png)

This result can be achieved by using a radiogroup rendered as checkboxes. My suggestions are the following:

1. Make the layout on the last image the default one.
2. Remove the `booleanRenderAs` property.
3. Add a flag for backward compatibility and give it a suitable name, for example, `useLegacyBooleanRendering`: true | false. We won't publish it but will give it to the customers who want the old, strange behavior.

**Comment by JaneGaid** [comment]
+1 https://github.com/surveyjs/survey-pdf/issues/170
