### ISSUE TITLE
Remove the `textFieldRenderAs` property

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-pdf#122]
The `textFieldRenderAs` property can be set to "singleLine" or "multiLine". Here's an image that illustrates the difference:

![](https://surveyjs.io/Documentation/images/SurveyPDF-options-textFieldRenderAs.png)

It's clear from this image that "singleLine" is worse than "multiLine" in all cases. Yet "singleLine" is the default mode. We should remove the `textFieldRenderAs` property and use multi-line rendering by default.

**Comment by JaneSjs** [comment]
+1 https://github.com/surveyjs/survey-pdf/issues/205

TODO: update the customer from the original thread if we change anything.
