### ISSUE TITLE
Question title formatted with html prints out as text including tags

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-pdf#13]
If a question title has html, the pdf renders the html as plain text including tags.

![image](https://user-images.githubusercontent.com/14329635/81047282-6521da00-8eba-11ea-9625-26fab4186746.png)

**Comment by hekin1** [comment]
Do you have any examples where the pdf-export formats the pdf-document correctly?

**Comment by gologames** [comment]
Hello,

As said in [SurveyPDF documentation](https://surveyjs.io/Documentation/Pdf-Export) to enable HTML support you need to add `onTextMarkdown` event processing via showdown MIT library. Here is [live sample in plunker](https://plnkr.co/edit/90vG6H5kTyhzLBVg) how to export PDF with HTML. Also look at [different types of HTML export in SurveyPDF](https://surveyjs.io/Documentation/Pdf-Export?id=HtmlToPdf)

Thanks, Alex
SurveyJS Team

**Comment by hekin1** [comment]
Thank you, this worked perfectly for me:

```
surveyPDF.onTextMarkdown.add((survey, options) => {
    var str = converter.makeHtml(options.text)
    options.html = str
})
```

I dont know why I didn't find that documentation in the first place, must've looked in the wrong places.

**Comment by shashankdesigner** [comment]
Hi, the above example converts text to html but aria-label and other attributes are also cotaining html tags. 
Any work around for this?

`aria-label="<p>p tag is not required in aria label</p>"`

**Comment by gologames** [comment]
Hello,

Could you @shashankdesigner, please, share us a live sample with the issue? We can't catch the idea why you are facing with `aria-label` when exports survey to PDF

Thanks, Alex
SurveyJS Team
