### ISSUE TITLE
how to change questions html title font color in export pdf file?

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-pdf#142]
### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the current behavior?
How do I change the font-color for question titles that have html?
I've added this code to change the color of normal questions without html-title:

```js
surveyPDF.onRenderQuestion.add((survey, options) => { 
        const plainBricks = options.bricks[0].unfold();
        for (const brick of plainBricks) {
            brick.textColor = "#000000";
        }
});
```
However this only works for questions without html title: Eg;
```js
{
     "type": "text",
     "name": "plainQuestion"
}
```
and it doesnt work for this question:
```
{
     "type": "text",
     "name": "question2",
     "title": "<p>This question has HTML title</p>"
}
```
Html gets default color #404040 and there seems no way to change it

### How would you reproduce the current behavior (if this is a bug)?
I made a plunker:

https://plnkr.co/edit/v3cOIcdprc12NVAQ

Press the save pdf button to see that html text is not changing color

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/v3cOIcdprc12NVAQ

### Specify your

* browser: firefox and chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.46

**Comment by JaneGaid** [comment]
Hello,
If you use HTML for a question title, specify the fore color in your HTML markup.

If you wish to colorize the title in PDF only, obtain a question using the `surveyPDF.getQuestionByName` function and modify the title HTML to add the `color` attribute:
```
var surveyPDF = new SurveyPDF.SurveyPDF(json, options);
var q2 = surveyPDF.getQuestionByName('question2');
var htmlString = q2.title;
var pEl = $(htmlString);
pEl[0].style = 'color="blue"';
q2.title = pEl.outerHTML;
```
The [updated example](https://plnkr.co/edit/8BEAHj3s43U93ZZa).

**Comment by hekin1** [comment]
Thanks for the reply @JaneSjs .

> If you wish to colorize the title in PDF only, obtain a question using the surveyPDF.getQuestionByName function and modify the title HTML to add the color attribute:

Yes I want to change the color only in the PDF. However, since there are 100's of question, the getQuestionByName will not work unfortunately. 

Best regards

**Comment by JaneSjs** [comment]
Hello @hekin1,
My apoligies for the delayed reply. 
Do I correctly understand that you export a survey with hundreds of questions?
Would you please clarify what you meant by 'the getQuestionByName will not work'? Do you mean that this function fails trying to get a question from your survey?

**Comment by hekin1** [comment]
> Do I correctly understand that you export a survey with hundreds of questions? 

yes

> Would you please clarify what you meant by 'the getQuestionByName will not work'? Do you mean that this function fails trying to get a question from your survey?

I need to change color of the questions that have HTML in them, since they somehow has another color (grey) compared to non-html question title's that are black.
If the question has a title with html tags, then it gets color #404040 
if there is no HTML in the title it gets color #000000

getQuestionByName will not help me, since I do not know the name of questions with html-tags in the title.

Best regards Henrik

**Comment by JaneSjs** [comment]
Hello @hekin1,
Please accept my apologies for the delayed reply. I believe you can use the [survey.onTextMarkdown](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onTextMarkdown) function of the Survey PDF instance and process HTML titles as required, for example, add an outer `div` and specify the `color` attribute for it.

Drop me a line if you have further questions.
