### ISSUE TITLE
How do I change all question title to normal thin font, not bold.

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-pdf#143]
### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the current behavior?
There is no way to change the question title to normal thin font-weight. All questions gets bold font

![Screenshot_2](https://user-images.githubusercontent.com/14329635/186880406-0899f23d-bc63-4233-923b-58656ca0ea0c.png)

### What is the expected behavior?
An option to change the default font style of questions in options. (or any other way) both html title and question name

```js
const options = {
        fontSize: 10,
        questionFontStyle: 'normal'
};
```

### Specify your

* browser: chrome and firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.46

**Comment by JaneGaid** [comment]
Hello,
Please try the following code (a complete example is available [here](https://codesandbox.io/s/survey-pdf-bold-question-titles-forked-96471l?file=/src/App.js)) to learn how to achieve this:
```
surveyPDF.onRenderQuestion.add((survey, options) => {
  const titleBrick = options.bricks[0].bricks[0];
  const titleBricks = titleBrick.unfold();
  const titleString = titleBricks.reduce((a, b) => a + b.text, "");
  const point = options.module.SurveyHelper.createPoint(titleBrick);
  point.yTop -= options.controller.margins.top;
  options.bricks[0].bricks[0] = options.module.SurveyHelper.createPlainTextFlat(
    point,
    options.question,
    options.controller,
    titleString,
    options.module.TextBrick
  );
});
```
For more information, refer to Serge T answer at [Un bold the question Titles](https://surveyjs.answerdesk.io/ticket/details/t10208/un-bold-the-question-titles).

**Comment by hekin1** [comment]
Hi @JaneGaid !
Thanks for you reply, I have tried the method specified in the answer (https://surveyjs.answerdesk.io/ticket/details/t10208/un-bold-the-question-titles)

However it does not work when combining html questions with plain text answers, as seen in this printscreen, the positions of the titles overlap and gets messed up
![bild](https://user-images.githubusercontent.com/14329635/189311386-a182e0ec-720b-414a-8fb2-df07a560622c.png)

Provided example code:
```js
    surveyPDF.onRenderQuestion.add((survey, options) => {
        const titleBrick = options.bricks[0].bricks[0];
        const titleBricks = titleBrick.unfold();
        
        if (titleBricks.some(t => t.hasOwnProperty("html"))) {
            // html title, dont touch
        } else {
            const titleString = titleBricks.reduce((a, b) => a + b.text, "");

            const point = options.module.SurveyHelper.createPoint(titleBrick);
            point.yTop -= options.controller.margins.top;
            options.bricks[0].bricks[0] = options.module.SurveyHelper.createPlainTextFlat(
                point,
                options.question,
                options.controller,
                titleString,
                options.module.TextBrick
            );

        }
    });
```

**Comment by JaneSjs** [comment]
In SurveyJS PDF Generator v3, question titles are not bold by default — they render in a regular weight.

If you do want to restyle titles (weight, size, color, italic), apply a theme or override the title in [`applyStyle()`](https://surveyjs.io/pdf-generator/documentation/api-reference/surveypdf#applyStyle):

```javascript
surveyPDF.applyStyle({
  question: {
    title: {
      fontStyle: "normal", // default in v3
      // fontWeight: "bold",
      // fontColor: "#1a1a1a"
    }
  }
});
```

You can try themes, light/dark palettes, and Compact/Spacious layout in the [PDF Generator demo](https://surveyjs.io/pdf-generator/examples/apply-surveyjs-theme-to-pdf-form/) — open the Theme settings panel with the button in the bottom-left corner.

For more information on how to apply predefined and custom styling to SurveyJS PDF, refer to [PDF Appearance Customization](https://surveyjs.io/pdf-generator/documentation/pdf-appearance-customization).

What's new in v3: [SurveyJS v3.0 — PDF Generator](https://surveyjs.io/stay-updated/major-updates/2025-2026#pdf-generator)
