### ISSUE TITLE
Matrixdynamic answers overwrite previous questions

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-pdf#145]
To reproduce the issue, [run this example](https://codesandbox.io/s/angry-chihiro-m09lui) and fill in survey questions:
![image](https://user-images.githubusercontent.com/22372972/187947148-603e794d-6bcd-473c-97d5-7ad673bd8678.png)

The PDF output:
![image](https://user-images.githubusercontent.com/22372972/187947104-3bd49829-2638-489e-ad78-010cf13cbf63.png)

The issue was originally reported at [T10490 - Export PDF - format when using matrixdynamic](https://surveyjs.answerdesk.io/internal/ticket/details/T10490).

**Comment by dk981234** [comment]
Seems to be problem with 'allowRowsDragAndDrop: true'.
