### ISSUE TITLE
Cannot select different options for Matrix question in PDF file

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-pdf#155]
Run [this demo](https://surveyjs.io/pdf-generator/examples/survey-pdf-export/reactjs) and export a form to PDF. In PDF, observe that initially, all rows of question 1 have valid answers. However, as soon as you start modifying individual row answers, you can no longer specify different answers for matrix rows:
![2022-10-13_12-34-15](https://user-images.githubusercontent.com/22372972/195560777-08dc67f8-0e15-430f-a2f3-14c1584f4a65.gif)

**Comment by dk981234** [comment]
For each matrix row's radiogroup will be generated id (/T): questionId + "_row_" + row.value  or questionId + "_row_"  + "index" + rowIndex if row's value was not specified.
