### ISSUE TITLE
Matrix radiobuttons print to PDF in rows

### ISSUE THREAD

**Issue by ironman1964** [surveyjs/survey-pdf#16]
Hi all,

I have a survey which contains a matrix of radiobuttons.
When I use the bootstrap theme and display it, it's ok
When I then print (from chrome) or save to pdf, it turns the matrix into separate rows.
Any clues how to fix ?

Using version 1.7.6 of library, bootstrap 3.3.7

if using the modern theme and css, it's ok ...

![Knipsel](https://user-images.githubusercontent.com/688083/82657132-25325500-9c25-11ea-918a-895c6cabdb41.PNG)

![Knipsel2](https://user-images.githubusercontent.com/688083/82657131-2499be80-9c25-11ea-87e1-f3afc2b97500.PNG)

**Comment by tsv2013** [comment]
Moved to the corresponding repo

**Comment by gologames** [comment]
Hello,

Unfortunately, printing web page (or saving pdf) via browser utils is not our responsibility. We can suggest you try our [SurveyPDF library](https://surveyjs.io/Documentation/Pdf-Export) (easy way export SurveyJS surveys to PDF)

Thanks, Alex
SurveyJS Team

**Comment by ironman1964** [comment]
SurveyPDF is a client-side script.
I need a server-side script ... for .NET C#
I used Rotativa/wkhtmltoPDF but that one lacked the jQuery execution
Now switched to SelectPDF (bit slow) it does the job perfect

**Comment by gologames** [comment]
Hello,

Unfortunately, all SurveyJS libraries is client side. We will discuss this situation with and I write back to this thread if I got any helpful information

Thanks, Alex
SurveyJS Team

**Comment by gologames** [comment]
Hello,

[Here is described](https://surveyjs.answerdesk.io/ticket/details/t2853/batch-export-pdf) some information about running SurveyPDF on server side with node.js. Feel free to contact us in case of any further questions

Thanks, Alex
SurveyJS Team
