### ISSUE TITLE
Save to PDF doesn't work for certain values

### ISSUE THREAD

**Issue by timblake78** [surveyjs/survey-pdf#166]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

PDF doesn't populate for certain values, even though they are completed in the survey

### What is the expected behavior?

PDF should populate with selected values.

### How would you reproduce the current behavior (if this is a bug)?

Created a Plunker - https://plnkr.co/edit/LabHWC33quhLOXHd

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/LabHWC33quhLOXHd

Test code

```
https://plnkr.co/edit/LabHWC33quhLOXHd

```

### Specify your

* browser:
Chrome

* browser version:
Version 106.0.5249.119 (Official Build) (arm64)

* surveyjs platform (angular or react or jquery or knockout or vue):
JQuery

* surveyjs version:
1.9.56

**Comment by JaneGaid** [comment]
Hello @timblake78,
Thank you for reporting this issue. We'll research it and post our updates.
For now, I would recommend that you specify the `value` property for your Radiogroup choices. Please try the updated example: https://plnkr.co/edit/oeVWAgGk0b1QZGIU.
