### ISSUE TITLE
Wrong encoding for the letter 'c' for variable "checked"

### ISSUE THREAD

**Issue by mikekidder** [surveyjs/survey-pdf#17]
The builds for **survey.pdf.js / survey.pdf.min.js** have an encoded character.  It is causing issues when saving the scripts locally (at least in US).  

Downloaded the source and found in the following lines:

https://github.com/surveyjs/survey-pdf/blob/4675e89237e95471e23bbb6fdb17f3733e9d9594/src/pdf_render/pdf_radioitem.ts#L24

https://github.com/surveyjs/survey-pdf/blob/4675e89237e95471e23bbb6fdb17f3733e9d9594/src/pdf_render/pdf_radioitem.ts#L35

Here is a screenshot when viewing the file via Baltic encoding:
![Annotation 2020-05-26 192627](https://user-images.githubusercontent.com/41694/82966191-7e80e800-9f87-11ea-9bf2-12224fe250db.png)

I corrected my own copy of files, and survey-pdf library works as expected.

**Comment by gologames** [comment]
Hello,

Indeed, this is a bug. We fixed it. Fix will available with next minor update

Thanks, Alex
SurveyJS Team
