### ISSUE TITLE
Fix IE11;  Ensure document.queryAllSelector returns an Array

### ISSUE THREAD

**Issue by mikekidder** [surveyjs/survey-pdf#18]
The following will return a NodeList in IE11 that is not directly an Array

https://github.com/surveyjs/survey-pdf/blob/aff1e0107ffc16b78364f088dbf8068e05598689/src/pdf_render/pdf_html.ts#L29

Consider using  
`Array.apply(null, document.querySelectorAll('iframe')).forEach(`
or
`[].call.slice(document.querySelectorAll('iframe')).forEach(`

I tested the first with Chrome / IE11

Since building from typescript/es6  --- could try Array.from?

**Comment by mikekidder** [comment]
FYI -- Edited above. Guess I didn't test Chrome.  So needs a little work to make sure works for all.

**Comment by gologames** [comment]
Hello,

We fixed that IE11 unable to forEach result of querySelectorAll query. This will available with next minor update

Thanks, Alex
SurveyJS Team
