### ISSUE TITLE
Change icon radio when export file pdf with question type radiogroup

### ISSUE THREAD

**Issue by Huuvinh94** [surveyjs/survey-pdf#19]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

When I export file pdf with question type radiogroup, icon same as below:
![image](https://user-images.githubusercontent.com/18391623/84101299-cf88e580-aa37-11ea-8395-aec1dd53a25e.png)

### What is the expected behavior?

I want export file pdf has circle icon as shown below:
![image](https://user-images.githubusercontent.com/18391623/84101266-bed86f80-aa37-11ea-8647-86869d980d75.png)

Is there any way to do that?
Thank a lot.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by gologames** [comment]
Hello,

If survey exports in edit mode, then unable to change appearance of the radiobutton, beacase it is rendered by the PDF viewer program. If survey exports in display mode, then you can override default appearance via [SurveyPDF adorners mechanism](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-adorners#content-docs). Here is example on our site where [checkbox render is overrided](https://surveyjs.io/Examples/Pdf-Export#content-js)

Thanks, Alex
SurveyJS Team

**Comment by Huuvinh94** [comment]
Hi @gologames 
Wow!!! It works very well.

Thanks you so much
