### ISSUE TITLE
[Error] Wrong font UI on PDF file when use ckeditor - markdown with custom font

### ISSUE THREAD

**Issue by PhuHoaframgia** [surveyjs/survey-pdf#194]
### Are you requesting a feature, reporting a bug or asking a question?

Bug (Wrong font UI on PDF file when use CKEDITOR - markdown with custom font for vietnamese, although The font is supported in Vietnamese)

### What is the current behavior?

Add some content of vietnamese on CKEDITOR then click download 

### What is the expected behavior?

Correct content on PDF file

#### Provide the test code and the tested page URL (if applicable)

This is my survey content:

![image](https://user-images.githubusercontent.com/23466462/218487718-a9d0935c-7d8b-401b-8701-b253b3d9a9c6.png)

This PDF file after download (wrong UI):

[surveyResult (9).pdf](https://github.com/surveyjs/survey-pdf/files/10723244/surveyResult.9.pdf)

![image](https://user-images.githubusercontent.com/23466462/218489149-be0f77f7-ed2d-4a82-8ae8-71005fcde648.png)

Tested page URL: https://codesandbox.io/s/shy-haze-mld8me?file=/src/SurveyPdfComponent.jsx

**Comment by JaneSjs** [comment]
@PhuHoaframgia,
You've done this correctly and registered a custom font family. To apply a custom font to the HTML content, wrap each HTML text entry with a <div> tag which declares a `style` attribute and set the `font-family` property to your custom font name (`myRoboto`). I suggest that you do this in the `doMarkdown` function:  `options.html = `<div style="font-family: myRoboto">${str}</div>``.
```
function doMarkdown(_survey, options) {
  if (options.name === "description") {
    //convert the markdown text to html
    let str = converter.makeHtml(options.text);
    if (str.indexOf("<p>") === 0) {
      //remove root paragraphs <p></p>
      str = str.substring(3);
      str = str.substring(0, str.length - 4);
    }
    // Set a custom font family
    options.html = `<div style="font-family: myRoboto">${str}</div>`;
  }
}
```
The updated example is available at https://codesandbox.io/s/old-glade-p7tvwf?file=/src/json.js.

I hope this helps.

Please free to reopen this thread if you have any questions.
