### ISSUE TITLE
Can a survey which has multiple pages be exported as a pdf with one page?

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-pdf#195]
### What is the current behavior?

I have a complex survey which has multiple pages where the route of the survey changes based on the answers  given. After  completing I'm exporting it as a pdf the pdf is generated the same way as the provided json with one question per page. Is there a way to create the pdf by merging several questions to one page?

![image](https://user-images.githubusercontent.com/26425777/218461527-ae60a4da-75e3-44c7-9f6b-e44e510408bc.png)

### What is the expected behavior?

Need a way to merge questions in several pages into one or couple of pages without too much space as shown in the image

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hi @OshaniSilva,
A [SurveyPDF](https://surveyjs.io/pdf-generator/documentation/api-reference/surveypdf) instance accepts a survey JSON definition. If you wish to compile all survey questions to a single page, you can process the original survey JSON, iterate through JSON elements and build a new one-page survey by adding all survey questions to a single page object.
For example, the original survey contains two pages:
```
const surveyJSON = {
  "pages": [    
    { "elements":[
        {
          "type": "rating",
          "name": "satisfaction",
          "title": "How satisfied are you with the Product?",
          "mininumRateDescription": "Not Satisfied",
          "maximumRateDescription": "Completely satisfied"
        }]},

        {"elements":[
        {
          "type": "rating",
          "name": "recommend friends",
          "visibleIf": "{satisfaction} > 3",
          "title": "How likely are you to recommend the Product to a friend or co-worker?",
          "mininumRateDescription": "Will not recommend",
          "maximumRateDescription": "I will recommend"
        }]}
  ]
};
```
You can process the survey JSON and generate a one-page survey:
```
 const onepageSurveyJson = {        
        "pages": [    
            { 
                "elements":
                [
                    {
                    "type": "rating",
                    "name": "satisfaction",
                    "title": "How satisfied are you with the Product?",
                    "mininumRateDescription": "Not Satisfied",
                    "maximumRateDescription": "Completely satisfied"
                    },
                    {
                    "type": "rating",
                    "name": "recommend friends",
                    "visibleIf": "{satisfaction} > 3",
                    "title": "How likely are you to recommend the Product to a friend or co-worker?",
                    "mininumRateDescription": "Will not recommend",
                    "maximumRateDescription": "I will recommend"
                    }
                ]    
            }
        ]
}
```
And initialize a SurveyPDF instance using the newly generated JSON:
```
const surveyPDF = new SurveyPDF.SurveyPDF(onepagejson, options);
```
[Example](https://plnkr.co/edit/ib9N6pWB3ABTjCPC).

Please feel free to reactivate this thread if you have any questions.
