### ISSUE TITLE
[Bug] Wrong UI PDF file for Strikethrough words, link and align text with CKEditor

### ISSUE THREAD

**Issue by PhuHoaframgia** [surveyjs/survey-pdf#198]
### Are you requesting a feature, reporting a bug or asking a question?

Bug 

1. Can't click to the link to redirect to new page 
2. Strikethrough is gone
3. wrong align when using align options
4. Number questions are gone for boolean question type (No sure because in my code, it's wrong but when use code sanbox - it works)

### What is the current behavior?

Correct content on preview

![image](https://user-images.githubusercontent.com/23466462/219691131-ade0ab0f-d2f3-4c9b-92e9-9eeb9ab5370d.png)

![image](https://user-images.githubusercontent.com/23466462/219691215-b9723153-97a3-481e-8736-4b2a61641b65.png)

but wrong UI on PDF

![image](https://user-images.githubusercontent.com/23466462/219686359-262b83f1-024d-42bb-9577-8993e3b54ea3.png)

#### Provide the test code and the tested page URL (if applicable)

my content

```
{
 "title": "My survey",
 "description": "<p>Le <a href=\"http://localhost:3000/survey/8baed537-94c7-44e2-a324-793fe3312980/designer\">Monde</a>&nbsp;and its <s><em><strong>partners</strong></em></s> may independently or jointly use cookies and similar (tổ chức và cộng đồng) <em>technologies during your visit to this site in order to gather information.</em></p><hr><p>including personal data, such as: IP address, unique identifiers, navigation data, geolocation data. hôm qua tôi đi chơi zui quá.&nbsp;cơ quan tổ chức, cá nhân và cộng đồng</p><ul>\t<li>data 1</li>\t<li>data 2</li></ul><table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" style=\"width:100%\">\t<tbody>\t\t<tr>\t\t\t<td>identifiers</td>\t\t\t<td>geolocation</td>\t\t</tr>\t\t<tr>\t\t\t<td>data</td>\t\t\t<td>navigation</td>\t\t</tr>\t\t<tr>\t\t\t<td>including</td>\t\t\t<td>address</td>\t\t</tr>\t</tbody></table><p><br><br><img alt=\"\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSalEj8tnk7AywBgsPErBHh2_8vFwc2yZty-mqmzy3t6pP_lN3WnokkH8ghoeFPZ13cs3g&amp;usqp=CAU\" style=\"height:100px; width:100px\"></p><p>&nbsp;</p>",
 "logoPosition": "right",
 "completedHtml": "<h3>Thanks</h3> ",
 "pages": [
  {
   "name": "Page 1",
   "elements": [
    {
     "type": "text",
     "name": "Question 1",
     "title": "Le Monde and its partners may independently or jointly use cookies and similar (tổ chức và cộng đồng) technologies during your visit to this site in order to gather information. including personal data, such as: IP address, unique identifiers, navigation data, geolocation data.",
     "description": "<p style=\"text-align:center\"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting<br>Remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"
    },
    {
     "type": "boolean",
     "name": "Question 2",
     "description": "<p style=\"text-align:justify\">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text,</p>"
    },
    {
     "type": "boolean",
     "name": "Question 3",
     "description": "<p style=\"text-align:right\">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don&#39;t look even slightly believable.&nbsp;</p>\n"
    },
    {
     "type": "checkbox",
     "name": "Câu hỏi 1",
     "choices": [
      "Item 2",
      "Item 1",
      "Item 3"
     ]
    }
   ]
  }
 ]
}
```

Tested page URL:

you can use align options here

https://cdn.ckeditor.com/4.14.1/full/ckeditor.js

https://codesandbox.io/s/elastic-tdd-8x6p5i?file=/public/index.html

Then get contend to download on this source

https://codesandbox.io/s/shy-haze-mld8me?file=/src/SurveyPdfComponent.jsx

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
Thank you for sharing the demo. I'll review it and get back to you shortly.

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
You may know that we use the [jspdf](https://github.com/parallax/jsPDF) library to export forms to PDF. To export HTML, we use the `fromHtml` function. We researched your example and it appears that all these issues are related to jspdf specifics.
For example, text is not center-aligned (check [this SO issue](https://stackoverflow.com/questions/42659769/jspdf-fromhtml-text-align-center-not-working)); links are not rendered: https://github.com/parallax/jsPDF/issues/1598.

Unfortunately, we cannot handle these issues at the moment. We may recommend that you consider using another way to convert HTML to PDF.

We appreciate your understanding. Please let me know if you have further questions.
