### ISSUE TITLE
Using "compress" option, causes responses not to be rendered in the PDF

### ISSUE THREAD

**Issue by lisadesouza89** [surveyjs/survey-pdf#203]
`function saveSurveyToPdf(filename, surveyModel, pdfWidth, pdfHeight) {
    var options = {
      fontSize: 12,
      margins: {
        left: 10,
        right: 10,
        top: 10,
        bot: 10
      },
      format: [pdfWidth, pdfHeight],
      compress: true, //Using this, responses not rendered - once commented, responses render fine
      htmlRenderAs: 'image', 
      commercial: true
    };
    var surveyPDF = new SurveyPDF.SurveyPDF(surveyJSON, options);
    surveyPDF.data = surveyModel.data;
    surveyPDF.save(filename);
  }
`

### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Responses not rendered using the "compress" option

### What is the expected behavior?
Responses should be rendered

### How would you reproduce the current behavior (if this is a bug)?
Detailed in code example comments

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```

<script src="https://unpkg.com/survey-jquery@1.9.55/survey.jquery.min.js"></script>
<script src="https://unpkg.com/survey-pdf@1.9.55/survey.pdf.min.js"></script>
function saveSurveyToPdf(filename, surveyModel, pdfWidth, pdfHeight) {
    var options = {
      fontSize: 12,
      margins: {
        left: 10,
        right: 10,
        top: 10,
        bot: 10
      },
      format: [pdfWidth, pdfHeight],
      compress: true, //Using this, responses not rendered - once commented, responses render fine
      htmlRenderAs: 'image', 
      commercial: true
    };
    var surveyPDF = new SurveyPDF.SurveyPDF(surveyJSON, options);
    surveyPDF.data = surveyModel.data;
    surveyPDF.save(filename);
  }

```

### Specify your

* browser: Microsoft Edge
* browser version: Version 110.0.1587.69 (Official build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.55

**Comment by JaneSjs** [comment]
Hello @lisadesouza89,
Thank you for reporting this issue. We will research it and let you know our results.

[Example](https://plnkr.co/edit/KbX3wDPRLteeQ9EK)

**Comment by JaneSjs** [comment]
Hi @lisadesouza89,
You may know that we use the jspdf library to export surveys and forms to PDF.
We quickly reviewed the issue, and it appears, that responses are not rendered because acro-forms (editable fields) are used to render survey question inputs and options; however, acro-forms are not supported in compressed PDF documents.

To resolve the issue, please enable the `display` mode for a Survey PDF instance:
```
surveyPDF.mode = "display";
```
Now, acro-forms won't be used to render question options, and responses will appear in PDF.

We'll look into how we can address this issue in our code.

Thank you
