### ISSUE TITLE
Display mode: Text values are truncated in a Matrixdropdown question

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-pdf#205]
[Original issue](https://surveyjs.answerdesk.io/internal/ticket/details/T12353)

[Example](https://plnkr.co/edit/7X3QOhe4NizqLinp).
Note: Set a Survey PDF to `display` mode to reproduce the issue.

**Comment by JaneSjs** [comment]
By default, single-text input fields are rendered in single line mode. Set the `textFieldRenderAs` property to `multiline`. Now, the text is rendered in multi-line mode and the text is fully displayed:

```
  let options = {
      fontSize: 14,
      textFieldRenderAs: "multiline",
      margins: {
        left: 10,
        right: 10,
        top: 10,
        bot: 10
   },              
   format: [pdfWidth, pdfHeight]
};
const surveyPDF = new SurveyPDF.SurveyPDF(json, options);

```

[Demo](https://plnkr.co/edit/sNMfKwKrMdmHtWcd)
