### ISSUE TITLE
Add an option to define a standard SurveyJS question renderer for a custom component

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#218]
[Example](https://codesandbox.io/s/amazing-fast-kb5lkq?file=/src/SurveyPdfComponent.jsx)

Add a new API function to get a PDF renderer / question for a custom defined question type from a [FlatRepository](https://github.com/surveyjs/survey-pdf/blob/5440d1c47dc57aba963cfb259bbb663c0bb55123/src/flat_layout/flat_repository.ts) class.

Instead of:
```
import { FlatRepository, FlatTextbox } from "survey-pdf";

FlatRepository.getInstance().register('color-picker', 
  FlatTextbox
);
```
Use a function to get a renderer by a specified type. For instance:
```
FlatRepository.getInstance().register(
  'color-picker',
  FlatRepository.getInstance().getRenderer("text")
);
```

**Comment by RomanTsukanov** [comment]
It would be great to implement an API without `getInstance()`:

```js
import { FlatRepository } from "survey-pdf";

FlatRepository.register(
  'color-picker',
  FlatRepository.getRenderer("text")
);
```
