### ISSUE TITLE
Export Pdf is not giving answers of the questions

### ISSUE THREAD

**Issue by binicr** [surveyjs/survey-pdf#23]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@binicr Could you please provide the example? It works in our example.

Thank you,
Andrew

**Comment by binicr** [comment]
Hi @andrewtelnov  ,Kindly share your example .I will try with that.

**Comment by andrewtelnov** [comment]
@binicr You can review them [here](https://surveyjs.io/Examples/Pdf-Export).

Thank you,
Andrew

**Comment by gologames** [comment]
Hello,

Current issue is covered by [this issue](https://github.com/surveyjs/survey-pdf/issues/25)

Thanks, Alex
SurveyJS Team
