### ISSUE TITLE
how to Configure license for SurveyJS for  save  to pdf option

### ISSUE THREAD

**Issue by binicr** [surveyjs/survey-pdf#24]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Can you specify - what do you mean?

**Comment by binicr** [comment]
Hi, @tsv2013  I have added export pdf option in viewer in survey.
But I need to configure surveyjs licence for allowing permission to export ,I mean I want to use it for commercial purpose.
so that Is there any configuration need to apply like license

**Comment by tsv2013** [comment]
Could you write us in our customer portal - https://surveyjs.answerdesk.io/ from the e-mail linked to your license? We'll answer you via the private ticket. Thank you for the understanding.

**Comment by binicr** [comment]
Hi @tsv2013 ,I have raised in  the portal.
https://surveyjs.answerdesk.io/ticket/details/t5192/configure-surveyjs-license-for-export-pdf-option-for-commercial-use

kindly help me as soon as possible

**Comment by tsv2013** [comment]
I've answered right now. Please check your mailbox.
