### ISSUE TITLE
An ability to cancel rendering empty questions

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-pdf#26]
Hello!

I cannot hide unanswered questions (question.isEmpty() === true) from the result PDF. Could you please advise me on a simple and correct approach?

**Comment by gologames** [comment]
Hello,

You can just traverse trough all questions via [getAllQuestions](https://surveyjs.io/Documentation/Library?id=surveymodel#getAllQuestions) method of SurveyPDF instance and then set [visible](https://surveyjs.io/Documentation/Library?id=Question#visible) property of question to `false` according to your business logic

Thanks, Alex
SurveyJS Team

**Comment by stsiushkevich** [comment]
> Hello,
> 
> You can just traverse trough all questions via [getAllQuestions](https://surveyjs.io/Documentation/Library?id=surveymodel#getAllQuestions) method of SurveyPDF instance and then set [visible](https://surveyjs.io/Documentation/Library?id=Question#visible) property of question to `false` according to your business logic
> 
> Thanks, Alex
> SurveyJS Team
