### ISSUE TITLE
Question : what means "No support of dynamic elements (visibleIf, buttons, validators, etc.)" on documentation ?

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-pdf#28]
I understand that elements with visibleIf , that depends for another questions are not allowed ????
If is this why you dont process the elements and visibleIfs before and send it as a parameter when is created the surveypdf ??

**Comment by andrewtelnov** [comment]
@jmar1998 Sorry, what do you mean? visibleIf/enableIf are supported. They are working on survey model level.

Thank you,
Andrew

**Comment by jmar1998** [comment]
oh so readme file is outdated
![image](https://user-images.githubusercontent.com/30509391/95203597-e28ba680-07da-11eb-9571-33d51ea15d73.png)

**Comment by andrewtelnov** [comment]
@jmar1998 Got it. If you change the value in the PDF document, for example opened in Adobe PDF Editor, then these functionalities will not work. Generated content in PDF is static.

Thank you,
Andrew
