### ISSUE TITLE
Handling of long answers for text input questions

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/survey-pdf#29]
Hi team,

We're currently using this project in our software to export survey responses. It works great however we're seeing an issue with the _text_ input questions specifically - essentially if the text is too long it is getting cut off. In the options the _mode_ is set to _display_ which seems to take care of the comment type questions (the box expands to accommodate), just not the text ones. Is this scenario handled currently?

Regards,
Aleks

**Comment by andrewtelnov** [comment]
@leksinteractive It renders correctly, html <input/> with "type" equals "text" and read-only atrribute. The problem that it renders text in one line and you can't scroll it. As a solution, you can convert "text" questions into comment if there are a lot of text.
Here is the  code snippets:
```js
var questions = survey.getAllQuestions();
for (var i = 0; i < questions.length; i++) {
    var obj = questions[i];
    if (obj.getType() == 'text' && !obj.isEmpty() && obj.value.length > 50) {
        var newQuestion = Survey.Serializer.createClass('comment');
        newQuestion.name = obj.name;
        newQuestion.fromJSON(obj.toJSON());
        var panel = obj.parent;
        var index = panel.elements.indexOf(obj);
        panel.removeElement(obj);
        panel.addElement(newQuestion, index);
    }
}
```
And here is [the example](https://plnkr.co/edit/4vHMMij0YXrMfEMx).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@leksinteractive I have just realized that this question is about PDF Export. Probably  @gologames finds a better solution.

Thank you,
Andrew

**Comment by gologames** [comment]
@leksinteractive I think in SurveyPDF you can use the same approach as my colleague suggest (just replace text questions to comment questions). Here is [live sample of this approach](https://plnkr.co/edit/ooeCxq3El0B1DM2b). Or you can perform the same task with [SurveyPDF adorners mechanism](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-adorners)

**Comment by leksinteractive** [comment]
Thank you @andrewtelnov @gologames - that works well 👍
