### ISSUE TITLE
Multiple Survey Export to PDF

### ISSUE THREAD

**Issue by scottmmack** [surveyjs/survey-pdf#30]
Hi,

I have multiple surveys in my jQuery JS. Only one survey is ever rendered. 
Is it possible to export only the survey that is rendered to PDF?

I'm using a similar method to this - 
http://plnkr.co/edit/eNLGKlekURbzvWQ8uCkC 

Any help would be great. 

Thanks,
Scott

**Comment by gologames** [comment]
Hello,

Unfortunately we can't understand you very clear. If you want export multiple SurveyJS surveys to one PDF document then you can merge several SurveyJSONs into one before export to PDF. Here is [live sample of this approach](https://plnkr.co/edit/aNIJW8J8yFKTPvDD)

Thanks, Alex
SurveyJS Team

**Comment by scottmmack** [comment]
Thanks for your response @gologames . Looks like your code could be used. Can't seem to get it compiling for larger surveys.
Code below for full survey - 

var surveyAcneJSON = {
    title: "Acne",
    completedHtmlOnCondition: [
        { expression: "{DermatologistCurrently} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{TreatmentPrescribed12weeks} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{Pregnant} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{HormonesPeriods} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{ExcessiveHairGrowth} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{BoilsNodulesPustules} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{ScarringMarksSkin} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{DistressEmbarassmentAnxiety} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{DistressEmbarassmentAnxiety} = 'No'", html: "<h1>Speak to Pharmacist</h1>" },
    ],
    pages: [
        {
            name: "Acne",
            elements: [
                {
                    type: "radiogroup",
                    name: "DermatologistCurrently",
                    title: "Are you known to a dermatologist for your acne currently?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "TreatmentPrescribed12weeks",
                    visible: false,
                    visibleIf: "{DermatologistCurrently} = 'No'",
                    title: "Have you been using a treatment for acne prescribed by a GP for more than 12 weeks?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "MaleFemale",
                    visible: false,
                    visibleIf: "{TreatmentPrescribed12weeks} = 'No'",
                    title: "Are you Male or Female?",
                    isRequired: true,
                    choices: [
                        { value: "Male", text: "Male" },
                        { value: "Female", text: "Female" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "Pregnant",
                    visible: false,
                    visibleIf: "{MaleFemale} = 'Female'",
                    title: "Are you (or could you be) currently pregnant?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "HormonesPeriods",
                    visible: false,
                    visibleIf: "{Pregnant} = 'No'",
                    title: "Sometimes this can be linked with hormones, have your periods been regular?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "ExcessiveHairGrowth",
                    visible: false,
                    visibleIf: "{HormonesPeriods} = 'No'",
                    title: "Do you suffer with excessive hair growth on your face, arms or body?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "BoilsNodulesPustules",
                    visible: false,
                    visibleIf: "{ExcessiveHairGrowth} = 'No' or {MaleFemale} = 'Male'",
                    title: "Does your acne include large boils, nodules or pustules?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "ScarringMarksSkin",
                    visible: false,
                    visibleIf: "{BoilsNodulesPustules} = 'No'",
                    title: "Does your acne leave scarring or permanent marks on your skin?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "DistressEmbarassmentAnxiety",
                    visible: false,
                    visibleIf: "{ScarringMarksSkin} = 'No'",
                    title: "Is it causing severe distress, embarassment or social anxiety?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
            ],
            description: "Please answer the following questions to determine the suitable outcome for you.",
        },
    ],
    triggers: [{ type: "complete" }],
    showNavigationButtons: "none",
    showPrevButton: false,
    showQuestionNumbers: "off",
    goNextPageAutomatic: true,
};
----------------------
Any help would be greatly appreciated,

Thanks,
Scott

**Comment by scottmmack** [comment]
`var surveyAcneJSON = {
    title: "Acne",
    completedHtmlOnCondition: [
        { expression: "{DermatologistCurrently} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{TreatmentPrescribed12weeks} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{Pregnant} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{HormonesPeriods} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{ExcessiveHairGrowth} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{BoilsNodulesPustules} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{ScarringMarksSkin} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{DistressEmbarassmentAnxiety} = 'Yes'", html: "<h1>See your GP</h1>" },
        { expression: "{DistressEmbarassmentAnxiety} = 'No'", html: "<h1>Speak to Pharmacist</h1>" },
    ],
    pages: [
        {
            name: "Acne",
            elements: [
                {
                    type: "radiogroup",
                    name: "DermatologistCurrently",
                    title: "Are you known to a dermatologist for your acne currently?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "TreatmentPrescribed12weeks",
                    visible: false,
                    visibleIf: "{DermatologistCurrently} = 'No'",
                    title: "Have you been using a treatment for acne prescribed by a GP for more than 12 weeks?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "MaleFemale",
                    visible: false,
                    visibleIf: "{TreatmentPrescribed12weeks} = 'No'",
                    title: "Are you Male or Female?",
                    isRequired: true,
                    choices: [
                        { value: "Male", text: "Male" },
                        { value: "Female", text: "Female" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "Pregnant",
                    visible: false,
                    visibleIf: "{MaleFemale} = 'Female'",
                    title: "Are you (or could you be) currently pregnant?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "HormonesPeriods",
                    visible: false,
                    visibleIf: "{Pregnant} = 'No'",
                    title: "Sometimes this can be linked with hormones, have your periods been regular?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "ExcessiveHairGrowth",
                    visible: false,
                    visibleIf: "{HormonesPeriods} = 'No'",
                    title: "Do you suffer with excessive hair growth on your face, arms or body?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "BoilsNodulesPustules",
                    visible: false,
                    visibleIf: "{ExcessiveHairGrowth} = 'No' or {MaleFemale} = 'Male'",
                    title: "Does your acne include large boils, nodules or pustules?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "ScarringMarksSkin",
                    visible: false,
                    visibleIf: "{BoilsNodulesPustules} = 'No'",
                    title: "Does your acne leave scarring or permanent marks on your skin?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "DistressEmbarassmentAnxiety",
                    visible: false,
                    visibleIf: "{ScarringMarksSkin} = 'No'",
                    title: "Is it causing severe distress, embarassment or social anxiety?",
                    isRequired: true,
                    choices: [
                        { value: "Yes", text: "Yes" },
                        { value: "No", text: "No" },
                    ],
                },
            ],
            description: "Please answer the following questions to determine the suitable outcome for you.",
        },
    ],
    triggers: [{ type: "complete" }],
    showNavigationButtons: "none",
    showPrevButton: false,
    showQuestionNumbers: "off",
    goNextPageAutomatic: true,
};`

**Comment by gologames** [comment]
Hello,

We'll investigate this issue and write back to this thread immediately 

Thanks, Alex
SurveyJS Team

**Comment by scottmmack** [comment]
Great thanks @gologames 👍

**Comment by gologames** [comment]
Hello,

We can't reproduce the issue. All works fine in our case. Here is [updated live sample with your SurveyJSON](https://plnkr.co/edit/mcrKUhBGCuScqmgK). Note, that `makeQuesionNamesUnique` function from this example can't work properly with your SurveyJSON, because you use question's names in `completedHtmlOnCondition` section and others

Thanks, Alex
SurveyJS Team
