### ISSUE TITLE
failed build on server

### ISSUE THREAD

**Issue by Bashar-Alziq** [surveyjs/survey-pdf#301]
RollupError: Could not resolve "../internals/define-window-property" from "../internals/define-window-property?commonjs-external"
##[error]65.04     at error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
##[error]65.04     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
##[error]65.04     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
i've had this error on pipeline since downloading survey-pdf library (am using version 1.9.130)

**Comment by JaneSjs** [comment]
Hello @Bashar-Alziq,
For us to move forward, we would ask you to post a problematic demo so that we can internally reproduce the issue and research it.

Thanks

**Comment by JaneSjs** [comment]
@Bashar-Alziq,
Unfortunately, I haven't received a response from you. Please let me know if you need any further assistance.

Thanks
