### ISSUE TITLE
Not printing result for boolean elements when valueTrue/valueFalse used.

### ISSUE THREAD

**Issue by vicsanca** [surveyjs/survey-pdf#31]
Hello.

While testing pdf library we found that bug.
A question like this:

      {
       "type": "boolean",
       "name": "test",
       "defaultValue": "false",
       "label": {
        "en": "test question"
       },
       "valueTrue": "1",
       "valueFalse": "0"
      }

produces this result 

{"test":"1"}

This works fine in browser but when printing to pdf with survey-pdf prints as false. pdf generation only works with {"test": true}
Should evaluate result against valueTrue and valueFalse for printing.

Thanks

**Comment by gologames** [comment]
Hello,

We will investigate this issue and write back to this thread immediately 

Thanks, Alex
SurveyJS Team

**Comment by gologames** [comment]
Hello,

We changed boolean value implementation in SurveyPDF to [checkedValue property](https://surveyjs.io/Documentation/Library?id=questionbooleanmodel#checkedValue). This fixes the issue which you had described. This will available with next minor update

Thanks, Alex
SurveyJS Team

**Comment by vicsanca** [comment]
Thanks :) for fast response.

Before opening another bug/question. For printing dates in user's locale we have to put some variable before generating? dates always are shown in US format. Still searching if is some problem in our side.
