### ISSUE TITLE
license key activation

### ISSUE THREAD

**Issue by Bashar-Alziq** [surveyjs/survey-pdf#320]
Dear SurveyJS Support Team,

I recently purchased a license key for SurveyJS. Could you please provide detailed instructions on how to integrate and activate the license key within my project?

Thank you for your assistance.

**Comment by JaneSjs** [comment]
Hello @Bashar-Alziq,
A license activation email has been sent to your account. You can also find instructions on how to add and activate a license within the [License Manager](https://surveyjs.io/manage) of your licensed account. 

Should you have any further questions, please feel free to reactivate this thread.

Thank you
