### ISSUE TITLE
File Upload - File Upload links appear messy

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#323]
T18792 - Export File Upload to PDF - Image Links do not appear clearly
https://surveyjs.answerdesk.io/internal/ticket/details/T18792
***
[View Demo](https://plnkr.co/edit/nicsKe0MXvCUNPQZ)

When uploading multiple files, file URLs appear as follows:
![image](https://github.com/surveyjs/survey-pdf/assets/22372972/1db07918-e39c-4e16-9cdd-8f6fdcc446f3)

You can see that it is difficult to distinguish file URLs.

Perhaps, consider displaying links as a list, i.e., one after the other.

**Comment by dk981234** [comment]
You can achieve this behavior via custom rendering of the file question.
Please, see an example: https://plnkr.co/edit/zmi8KwqctdtkT8KO
