### ISSUE TITLE
Right single quotation mark, U+2019 ( ’ ) causes garbage

### ISSUE THREAD

**Issue by JauresC** [surveyjs/survey-pdf#327]
When you add a "Right single quotation mark", U+2019, to an HTML element, the pdf will output these characters in front of the line : þÿ

The font of the text containing the \u2019 character will also change.

Exemple of the bug :
https://plnkr.co/edit/wBOu9pqtrM6BOcUB

Character causing it :
https://www.compart.com/fr/unicode/U+2019

**Comment by JaneSjs** [comment]
Hello @JauresC,
Thank you for a demo.
The SurveyJS PDF Generator uses a third-party [jsPDF](https://github.com/MrRio/jsPDF) library to export surveys to PDF. By default, jsPDF supports a set of fonts known as the [standard (or base) 14 PDF fonts](https://en.wikipedia.org/wiki/PDF#:%7E:text=Fourteen%20typefaces%2C%20known%20as%20the,oblique%2C%20bold%20and%20bold%20oblique).

However, the predefined set of fonts may not include glyphs for special characters. Therefore, if you wish to use special characters in PDF surveys, you need to ensure that a SurveyJS PDF instance can access a font which contains required glyphs. To ensure that custom characters appear correctly, consider [registering a custom font](https://surveyjs.io/pdf-generator/documentation/customize-pdf-form-settings#custom-fonts).

Besides, you can choose the [image HTML export mode](https://surveyjs.io/pdf-generator/documentation/customize-survey-question-rendering-in-pdf-form#html-rendering).
```
const pdfDocOptions = {
      htmlRenderAs: "image"
};
const surveyPDF = new SurveyPDF.SurveyPDF(json, pdfDocOptions);
``` 
[View Demo](https://plnkr.co/edit/2BeTUAQwZWF6mX1H)

Alternatively, simply replace a special sign by a suitable glyph which is included to a set of standard font glyphs.
```
const json = {
    "pages": [{
            "name": "Introduction",
            "elements": [{
                    "type": "html",
                    "name": "question1",
                    "html": "Hellohello<br>Hello'hello"
                }
            ],
            "title": "Introduction"
        }
    ]
}
```
[View Demo](https://plnkr.co/edit/Hvnoo6CdseoWEvgX)

Feel free to reopen this thread if you have more questions.
