### ISSUE TITLE
Long text in comment in display mode doesn't render in PDF correctly

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-pdf#328]
T19279 - Text in "comment" question type overlaps the footer
https://surveyjs.answerdesk.io/internal/ticket/details/T19279
***
Here is [the example](https://plnkr.co/edit/xZj28fkt1HllOOyr) that doesn't work correctly.

**Comment by JaneSjs** [comment]
A customer request to render a large Comment text as plain text on multiple pages and to render a border around each part of the text.
T19679 - Converting comment to as flat question default - but I also need board to ther container div
https://surveyjs.answerdesk.io/internal/ticket/details/T19679
