### ISSUE TITLE
Issue with Surveyjs-pdf - Uncaught (in promise) TypeError: u.generateFlatItem is not a function

### ISSUE THREAD

**Issue by zenricatlasopen** [surveyjs/survey-pdf#329]
**Survey json:** 
[pre-emp safety critical.txt](https://github.com/user-attachments/files/16685132/pre-emp.safety.critical.txt)

**Issue I got:**
This might be related to **matrix dropdown** question types in this particular survey
![image](https://github.com/user-attachments/assets/605bf165-4b0c-4142-9553-0b454d82c2e1)

* browser: Chrome
* browser version: 127.0.6533.120
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 

![Screenshot 2024-08-21 101525](https://github.com/user-attachments/assets/66c4010f-6180-4331-9d75-527b2f55cf1e)

**Comment by JaneSjs** [comment]
Hello @zenricatlasopen,
Thank you for reporting this issue. I managed to reproduce it in v1.11.12 ([View Demo](https://plnkr.co/edit/qTx0ULAkJrqCQRBL)).
```
Uncaught (in promise) TypeError: u.generateFlatItem is not a function
    at e.<anonymous> (survey.pdf.min.js:6:69114)
    at i (survey.pdf.min.js:6:2176)
    at Object.next (survey.pdf.min.js:6:1480)
    at survey.pdf.min.js:6:1414
    at new Promise (<anonymous>)
    at r (survey.pdf.min.js:6:1211)
    at e.generateFlatsCell (survey.pdf.min.js:6:68694)
    at e.<anonymous> (survey.pdf.min.js:6:71580)
    at i (survey.pdf.min.js:6:2176)
    at Object.next (survey.pdf.min.js:6:1480)
```
We'll work on this issue and let you know once the fix is available.

**Comment by zenricatlasopen** [comment]
matrix question of this page - _K10 Mental Health Questionnaire_

**Comment by zenricatlasopen** [comment]
https://www.loom.com/share/44e27f01b6134f379b45302b569b3d48

**Comment by zenricatlasopen** [comment]
`show in multiple columns `option from row cell is checked
![image](https://github.com/user-attachments/assets/df665a92-3074-43dd-ab51-0ebb89d5b89d)
