### ISSUE TITLE
Radiogroup - A circle mark is misaligned in read-only PDF mode when a custom font is used

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#340]
T20162 - The dot isn't in the middle when using custom fonts for the PDF.
https://surveyjs.answerdesk.io/internal/ticket/details/T20162
***
[View Demo](https://codesandbox.io/p/sandbox/affectionate-ride-sj5xpq?file=%2Fsrc%2FSurveyPdfComponent.jsx%3A25%2C5)

In editable mode:
![image](https://github.com/user-attachments/assets/f7e1a81a-c969-4bb4-990a-55f5189a8941)

In read-only mode:
![image](https://github.com/user-attachments/assets/d24ebe91-0a0e-487f-af5e-7bfaa0da40c8)

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
