### ISSUE TITLE
Update boilerplate to support jspdf's recent updates. Unable to serve the app.

### ISSUE THREAD

**Issue by varundhariyal** [surveyjs/survey-pdf#36]
Please look into the issue
jspdf recent versions have modified dist structure.

Update code or provide jspdf'version version in package.json.

![Screenshot from 2021-02-22 15-49-15](https://user-images.githubusercontent.com/28480232/108695021-cf793900-7525-11eb-9792-4b87f4ed0499.png)

**Comment by gologames** [comment]
Hello,

We will investigate this issue and write back to this thread immediately 

Thanks, Alex
SurveyJS Team

**Comment by dk981234** [comment]
Hello,

We've updated the boilerplate. Now it works fine with the newest survey-pdf package.

Thanks,
Dmitry
SurveyJS Team

**Comment by swapnil0545** [comment]
Still facing same error with latest code 
![image](https://user-images.githubusercontent.com/5073982/111262047-88282900-8649-11eb-84ad-a454b4bbb4f9.png)

**Comment by gologames** [comment]
Hello,

We will check it again and write back to this thread

Thanks, Alex
SurveyJS Team

**Comment by gologames** [comment]
Hello,

We updated `package-lock.json` file of our [Angular Quickstart Boilerplate](https://github.com/surveyjs/surveyjs_angular_cli) via [this commit](https://github.com/surveyjs/surveyjs_angular_cli/commit/50975f16ea418a180062a3078359c877bce8b214). Please, pull last commit of repository, remove `node_modules` folder (if exist) and try to `npm i` and `npm start` again

Thanks, Alex
SurveyJS Team
