### ISSUE TITLE
Is it possible to modify the style used by survey-pdf to render matrix questions?

### ISSUE THREAD

**Issue by kroehne** [surveyjs/survey-pdf#39]
### Are you requesting a feature, reporting a bug or asking a question?

I'm asking a question: Is it possible to modify the style used by survey-pdf to render matrix questions?

### What is the current behavior?

Columns in matrix questions are equally spaced.

### What is the expected behavior?

Columns for the responses should be smaller compared to the first column that contains the question text. For the presentation the desired presentation can be achieved using the following css (i.e., by using a smaller value for min-width):

````
<style>
.sv_main .sv_container .sv_body .sv_p_root table.sv_q_matrix td {
	min-width: 5em;
}
</style>
```` 

Is it possible to adjust the PDF rendering in a similar way?

Thanks and kind regards.

**Comment by gologames** [comment]
Hello,

Let me describe the situation, please. Unfortunately these is no browser engine inside PDF document. So it is unable to use CSS styles there. We use Adobe Acroforms to render editable forms and use special render for readonly mode

You cad [widely customize](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-customstylization) resulted PDF document with[ SurveyPDF Adorners mechanim](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-adorners). Feel free to contact us in case of further questions 

Thanks, Alex
SurveyJS Team
