### ISSUE TITLE
Angular PDF does not contain values

### ISSUE THREAD

**Issue by wollerman** [surveyjs/survey-pdf#4]
I was trying to test generating PDFs using `survey-pdf` in Angular, and I haven't been able to get the values to render. So then I decided to look at the documentation here: https://surveyjs.io/Examples/Library/?id=survey-data&platform=Angular2

And if you hit `complete` and look at the `pdf` tab it also does not contain the values. This is compared to https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery which _does_ contain the survey values. So it seems there is a bug related to angular when filling the values?

**Comment by gologames** [comment]
Hello,

Unfortunately there are some compatibility problem with jsPDF (which SurveyPDF use) and zone.js (which Angular use). Detailed explanation and [workaround here](https://surveyjs.answerdesk.io/ticket/details/t2319/answeres-not-rendered-correct)

Thanks, Alex
SurveyJS Team
