### ISSUE TITLE
Unicode in onTextMarkdown

### ISSUE THREAD

**Issue by kroehne** [surveyjs/survey-pdf#40]
### Are you requesting a feature, reporting a bug or asking a question?

How to encode Unicode characters in surveyPDF.onTextMarkdown?

### What is the current behavior?

Unicode characters (in markdown contexts) are not rendered correctly.

### How would you reproduce the current behavior (if this is a bug)?

<pre><code>surveyPDF.onTextMarkdown.add(function (survey, options) {
                        var str = converter.makeHtml(options.text);
                        str = str.substring(3);
                        str = str.substring(0, str.length - 4);
                        str = str  + "…" + "&#8230;"; 
                        options.html = str;
                    });
</code></pre>

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/YEpDFmepdOlFQ23A?preview

**Comment by gologames** [comment]
Hello,

Unfortunately, our `"standard"` HTML to PDF render works wrong for symbols like `…` (more about HTML to PDF [here](https://surveyjs.io/Documentation/Pdf-Export?id=HtmlToPdf)). Our HTML to image render doesn't supported for question's titles and descriptions at this moment

At the same time we enhanced HTML to image render to avoid strange scale and padding [via this commit](https://github.com/surveyjs/survey-pdf/commit/64189f64dcb3cf1acafc79a844fd002d3fdedd1c). So we will try to add support of this render for question titles/descriptions. We'll update this thread after investigation

![image](https://user-images.githubusercontent.com/30930391/114054959-fce13280-9898-11eb-95de-f24d6b4321c1.png)


Thanks, Alex
SurveyJS Team

**Comment by gologames** [comment]
Hello,

We implemented ability to use custom fonts via [this commit](https://github.com/surveyjs/survey-pdf/commit/7a84c922eb83098c50785a47956d38ce555afb0e). You can check this with [next minor update](https://surveyjs.io/WhatsNew)

Thanks, Alex
SurveyJS Team
