### ISSUE TITLE
Bug saving survey that contains html question that has two line break elements

### ISSUE THREAD

**Issue by DrewHoo** [surveyjs/survey-pdf#43]
### Are you requesting a feature, reporting a bug or asking a question?
I am reporting a bug

### What is the current behavior?
Trying to save a file with the above question results in an error: 
```
error TypeError: Cannot read property '1' of undefined
    at Renderer.renderParagraph (/node_modules/survey-pdf/survey.pdf.js:10400)
    at Renderer.setBlockBoundary (/node_modules/survey-pdf/survey.pdf.js:10458)
    at DrillForContent (/node_modules/survey-pdf/survey.pdf.js:9961)
    at DrillForContent (/node_modules/survey-pdf/survey.pdf.js:9924)
    at DrillForContent (/node_modules/survey-pdf/survey.pdf.js:9924)
    at eval (/node_modules/survey-pdf/survey.pdf.js:10114)
    at done (/node_modules/survey-pdf/survey.pdf.js:9975)
    at loadImgs (/node_modules/survey-pdf/survey.pdf.js:10012)
    at process (/node_modules/survey-pdf/survey.pdf.js:10111)
    at Object.jsPDFAPI.fromHTML (/node_modules/survey-pdf/survey.pdf.js:10545)
```
### What is the expected behavior?
The file saves successfully

### How would you reproduce the current behavior (if this is a bug)?
Try to save a survey that includes a question like this:
```
{
  "type": "html",
  "name": "anchor",
  "html": "<h2>a<br /><br />a</h2>"
}
```
A MCVE can be found in the following plunker: https://plnkr.co/edit/sod77jzExVxEwV82
It is just the code from the [Save Options example](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-saveoptions&platform=Knockoutjs&theme=modern#content-result), opened in plunker, with the question above added.

A weird thing I noticed, if you add an anchor element with a target, the file will save, e.g. this saves:
```
{
  "type": "html",
  "name": "anchor",
  "html": "<h2><a target=\"\\&quot;_blank\\&quot;\"></a>a<br /><br />a</h2>"
}
```

* browser: Chrome
* browser version: Version 90.0.4430.85 (Official Build) (x86_64)
* surveyjs platform (angular or react or jquery or knockout or vue): this happens on react and knockout
* surveyjs version: latest (1.8.46)

**Comment by gologames** [comment]
Hello,

In SurveyPDF we use `fromHTML` method of `jsPDF` MIT library. Unfortunately, it has a lot of constraints. At the same time according to [HTML5 specification](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element) duplication of `<br>` tag as in your HTML value is not recommended (and no guarantee of proper work for this case)

As a workaround you can add empty element between `<br>` tags like this `<h2>a<br /><div></div><br />a</h2>` or use HTML to PDF image render with `htmlRenderAs: 'image'` option for more stable work. You can find more information about HTML to PDF render in SurveyPDF [here](https://surveyjs.io/Documentation/Pdf-Export?id=HtmlToPdf)

Thanks, Alex
SurveyJS Team

**Comment by DrewHoo** [comment]
This is really helpful, thanks!
