### ISSUE TITLE
Subsequent generation results in file growing with constant rate

### ISSUE THREAD

**Issue by hannes-justsolve** [surveyjs/survey-pdf#44]
Greetings fellow humans,

I've run into an issue that could be a bug or my own incompetence. Please have a look at the following and help a brother out.

Kind regards,
Hannes

### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug or need to learn how to code

### What is the current behavior?
On subsequent calls to functions to generate the PDF, the resulting files grow with a constant rate.

### What is the expected behavior?
Given the same inputs, subsequent calls should result in identical files.

### How would you reproduce the current behavior (if this is a bug)?
Test code below reproduces the bug

#### Provide the test code and the tested page URL (if applicable)
Test code
```
const fs = require('fs/promises')
const SurveyPDF = require("survey-pdf")

async function GenDoc(fn) {
    const doc = {
        "pages": [
            {
                "name": "page1",
                "elements": [
                    {
                        "type": "text",
                        "name": "question1"
                    }
                ]
            }
        ]
    };

    const options = {
        fontSize: 12,
        margins: {
            left: 10,
            right: 10,
            top: 18,
            bot: 10,
        }
    }

    const surveyPDF = new SurveyPDF.SurveyPDF(doc, options);

    surveyPDF.mode = "display";

    await fs.writeFile(`${Date.now()}-${fn}-RAW.pdf`, Buffer.from(await surveyPDF.raw("arraybuffer")));
    surveyPDF.save(`${Date.now()}-${fn}-SAVE.pdf`);
}

async function main() {
    try {
        for (let i = 1; i <= 3; i++)
            await GenDoc(i);
    }
    catch (ex) {
        console.error(ex)
    }
}

main();
```

#### Outputs
```
ls -hl *.pdf
-rw-r--r-- 1 Hannes 197121 186K May 11 16:24 1620743080619-1-RAW.pdf
-rw-r--r-- 1 Hannes 197121 297K May 11 16:24 1620743080977-1-SAVE.pdf
-rw-r--r-- 1 Hannes 197121 406K May 11 16:24 1620743081157-2-RAW.pdf
-rw-r--r-- 1 Hannes 197121 517K May 11 16:24 1620743081793-2-SAVE.pdf
-rw-r--r-- 1 Hannes 197121 627K May 11 16:24 1620743082043-3-RAW.pdf
-rw-r--r-- 1 Hannes 197121 738K May 11 16:24 1620743082836-3-SAVE.pdf
```

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): Node 14.16.1
* surveyjs version:
  - jspdf: "^2.3.1"
  - survey-core: "^1.8.47"
  - survey-pdf: "^1.8.47"

**Comment by gologames** [comment]
Hello,

Could you, please, share us a live sample (in plunker for example) with the issue? So we can investigate it

Thanks, Alex
SurveyJS Team

**Comment by hannes-justsolve** [comment]
Hi Alex,

Thank you, I'll set something up and give feedback shortly.

Hannes

**Comment by gologames** [comment]
Hello,

We'll check link which you had provided and write back to this thread immediately 

Thanks, Alex
SurveyJS Team

**Comment by gologames** [comment]
Hello,

Reproduced the issue in your live sample. We will back to this thread after any results

Thanks, Alex
SurveyJS Team

**Comment by hannes-justsolve** [comment]
Hi,

Just linking back to your support portal: Question T7018

Kind regards,
Hannes

**Comment by matthew-healthtrack** [comment]
Hi,

Just wondering if there was any update on this issue or any workarounds found in the meantime? 

Regards,
Matthew

**Comment by gologames** [comment]
Hello,

The issue was with adding default font to PDF document multiple times. We fixed it with commit mentioned above. Thank you guys for your attention to the problem. Fix will be available with [next minor update](https://surveyjs.io/WhatsNew)

Thanks, Alex
SurveyJS Team
