### ISSUE TITLE
Unused npm-dts

### ISSUE THREAD

**Issue by vytenisu** [surveyjs/survey-pdf#5]
Noticed you are using npm-dts in your package.json file. You might want to integrate it or remove as an unused dependency. Integration is straightforward.

Since you use Webpack - I would recommend using https://www.npmjs.com/package/npm-dts-webpack-plugin instead.

**Comment by gologames** [comment]
Hello,

We removed unused dependencies from package.json [via this commit](https://github.com/surveyjs/survey-pdf/commit/e1ee21aa758de93f3d212ac0915e7ee186543599)

Thanks, Alex
SurveyJS Team
