### ISSUE TITLE
How can I add a cover page? Please add some utilities for this basic needs.

### ISSUE THREAD

**Issue by emidiotorre** [surveyjs/survey-pdf#52]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question, and requesting a feature.

### What is the current behavior?
I render a PDF, and everything is working fine.

### What is the expected behavior?
I need to add a cover image, i can draw a png on header and footer, and would like to add an initial page, and just draw the image.

**Comment by gologames** [comment]
Hello,

If you want to add extra first page with full page image, then you can do following:
1) [Add new page](https://surveyjs.io/Documentation/Library?id=surveymodel#addNewPage) to SurveyPDF object before export survey to PDF (call [save](https://surveyjs.io/Documentation/Pdf-Export?id=surveypdf#save) method)
2) Add empty [HTML question](https://surveyjs.io/Examples/Library?id=questiontype-html) to this page (to make the page visible)
3) Use [onRenderHeader event](https://surveyjs.io/Documentation/Pdf-Export?id=surveypdf#onRenderHeader) of render headers and footers mechanism ([description](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-header#content-docs), [article](https://surveyjs.io/Documentation/Pdf-Export?id=Customization-CustomRender-HeaderFooter)) to draw full page image (also this trick used [here](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-customstylization))

Here is [live sample of this approach](https://plnkr.co/edit/gb5ZKeiRV50q0Uf2?preview)

![image](https://user-images.githubusercontent.com/30930391/124281004-f8ec4600-db51-11eb-8ebe-29c4b055e8ed.png)


Thanks, Alex
SurveyJS Team
