### ISSUE TITLE
Add the ability to hide borders in text questions

### ISSUE THREAD

**Issue by ST-1580** [surveyjs/survey-pdf#63]

**Comment by aldwnesx** [comment]
Is this usable?

**Comment by ST-1580** [comment]
Hello @aldwnesx,

Unfortunately, this functionality is not availably in the current moment. We will update this thread after implementation the feature.

Thanks, Yaroslav
SurveyJS Team

**Comment by ST-1580** [comment]
Hello, @aldwnesx 

We've implemented `FORM_BORDER_VISIBLE` constant (`true` by default). Now you can set `SurveyHelper.FORM_BORDER_VISIBLE = false;` to hide borders of all questions. Here is [live sample in plunker](https://plnkr.co/edit/Dwx23Q8doGUnBCNl)

Short documentation information (for @HenriTroyot too). Survey example with `FORM_BORDER_VISIBLE` equals `true`:

![image](https://user-images.githubusercontent.com/15248977/131522295-8973c75e-23df-4135-a58d-20720ce4b7c3.png)

And survey example with `FORM_BORDER_VISIBLE` equals `false`:

![image](https://user-images.githubusercontent.com/15248977/131523059-0428cf0f-4c6a-4d73-ad01-e89425955147.png)


Thanks, Yaroslav
SurveyJS Team
