### ISSUE TITLE
Comments with tabulation in its value render wrong

### ISSUE THREAD

**Issue by ST-1580** [surveyjs/survey-pdf#65]
Here is [corresponding issue in Plunker](https://plnkr.co/edit/pU8UXNg0tlIOK1Yy)

![image](https://user-images.githubusercontent.com/15248977/127662341-8765b741-2fde-4386-8b9c-3227a44cccd0.png)

**Comment by johnyzv** [comment]
@dk981234 Is this fixed now?

**Comment by dk981234** [comment]
Hello, 
I am sorry. We've not fixed the issue yet. We'll write you back if there are any updates on this issue.

Thanks,
Dmitry
SurveyJS Team

**Comment by ST-1580** [comment]
Hello, @johnyzv

We've fixed this issue via the commit above. 

Unfortunately, the problem was in jsPdf library which we are using to render pdfs. This library can't escape text with some fonts and our default pdf font is one of these. So, now we escape  text before its rendering by yourself. Tabulation symbol is escaped as four non-breaking spaces.

This functionality will be available in the nearest update. 

Thanks,
Yaroslav
SurveyJS Team
