### ISSUE TITLE
Render Custom Page

### ISSUE THREAD

**Issue by aldwnesx** [surveyjs/survey-pdf#66]
How can i create a custom page in the pdf? I want to be able to show some contents that is not part of the survey, and then the following pages the survey result.

**Comment by gologames** [comment]
Hello,

The solution depends on your goal. First of all you can add extra page to `SurveyPDF` before export survey to PDF. You can find [here](https://surveyjs.answerdesk.io/ticket/details/t6984) and [here](https://github.com/surveyjs/survey-pdf/issues/29) more information about this approach. Also you can use SurveyPDF Adorners mechanism (described [here](https://surveyjs.io/Documentation/Pdf-Export?id=Customization-Options) and [here](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-adorners#content-docs)). [This](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-customstylization) and [this](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-adorners) are examples. Feel free to contact us in case of any further questions

Thanks, Alex
SurveyJS Team
