### ISSUE TITLE
Export to PDF, same style as what's shown on the web page?

### ISSUE THREAD

**Issue by aldwnesx** [surveyjs/survey-pdf#70]
How can I export the survey to pdf with the same style as  the survey form?  

```
Survey
    .StylesManager
    .applyTheme("modern");
```

I have tried manually designing as such:
https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-customstylization&platform=jQuery&theme=modern#content-js

but it is too confusing and I am getting error Uncaught (in promise) Error: Invalid arguments passed to jsPDF.text

Is there a default style for export to pdf so it doesn't look plain?

**Comment by tsv2013** [comment]
PDF export from SurveyJS doesn't support themes. You can customize styles as shown in the example you mentioned.

**Comment by JaneSjs** [comment]
With SurveyJS PDF Generator v3, your web forms and PDF documents look much closer to their web counterparts. Colors, fonts, spacing, and overall layout have been refined, so users experience a consistent design whether they're filling out a SurveyJS form online or reviewing it as a PDF.

<img width="1544" height="934" alt="Image" src="https://github.com/user-attachments/assets/9a0cb63f-051c-4b6d-946c-ac3604f3141d" />

PDF Generator uses the same design tokens as SurveyJS Form Library, so an exported PDF can match the form on the page. Apply one SurveyJS theme to both the web form and `SurveyPDF`—pick a predefined theme or bring your own custom theme JSON—and colors stay in sync, including light and dark palettes.

Layout is independent of color. Choose **Compact** (the default: denser, fewer pages) or **Spacious** (more open, easier to read) depending on whether you care more about page count or breathing room.

See it in the [PDF Generator demo](https://surveyjs.io/pdf-generator/examples/apply-surveyjs-theme-to-pdf-form/). Open the Theme settings panel with the button in the bottom-left corner, switch the theme, light/dark palette, and Compact/Spacious layout, then download or preview the PDF. To brand the document yourself, start from [Create a Custom Theme for a PDF Form](https://surveyjs.io/pdf-generator/examples/create-custom-pdf-form-theme/).

When theme and layout are not enough—custom fonts, padding, borders, or per-question tweaks—use `applyStyle()` and `applyLayout()`. Full details are in our documentation:
* [PDF Appearance Customization](https://surveyjs.io/pdf-generator/documentation/pdf-appearance-customization)
* [Themes](https://surveyjs.io/documentation/themes-and-custom-styles)

What's new in v3: [SurveyJS v3.0 — PDF Generator](https://surveyjs.io/stay-updated/major-updates/2025-2026#pdf-generator).
