### ISSUE TITLE
SurveyPDF on a server-side framework - Make the library compatible with Node.js

### ISSUE THREAD

**Issue by swapnil0545** [surveyjs/survey-pdf#72]
This is a feature request. Currently we are creating the pdfs on the server side. But it seems that this library is using window and document objects at some places and hence the pdf doesn't get created when using those components.
Would like to have the nodejs support  for it.

**Comment by gologames** [comment]
Hello,

We already [have a task](https://github.com/surveyjs/survey-pdf/projects/1#card-21940691) to research support server rending for SurveyPDF. Here is [corresponding ticket](https://surveyjs.answerdesk.io/ticket/details/t2853) in our support center. We will update this thread in case any progress or information about this feature

Thanks, Alex

**Comment by pbros** [comment]
Hello,

Has there been any progress made on server-side rendering of SurveyJS PDF? 

We're looking at building an automated archival of the results of surveys as PDFs. To do this, we would need a way to generate a PDF of the survey and responses without the need of a user's web browser, hence using nodejs in the backend.

Thanks

**Comment by JaneSjs** [comment]
+1 

T14181 - html formatting issue when generating pdf
https://surveyjs.answerdesk.io/internal/ticket/details/T14181

**Comment by JaneSjs** [comment]
Hello,
Just want to inform you that we published an example on how to export a sample survey on Node.js environment: [Create PDF Forms in Node.js](https://github.com/surveyjs/code-examples/tree/main/surveyjs-pdf-nodejs). 

Please take note of a [limitation regarding the question types unsupported on Node.js](https://github.com/surveyjs/code-examples/tree/main/surveyjs-pdf-nodejs#limitations).

We hope this example may help. Should you have any questions or require further assistance, we are here to help.
