### ISSUE TITLE
pdf is not rendering the widgets and is not setting the answers

### ISSUE THREAD

**Issue by gustavo-campos** [surveyjs/survey-pdf#9]
components I'm using and their versions

   "survey-angular": "1.5.17",
    "survey-creator": "1.5.17",
    "survey-knockout": "1.5.17",
    "survey-pdf": "1.5.17",
    "surveyjs-widgets": "1.5.17"

    code as I'm generating the pdf

    const surveyPDF = new SurveyPDF.SurveyPDF(SurveyJson, options);
    console.log(this.DxFormData.AnswerJson);
    surveyPDF.data = this.DxFormData.AnswerJson;
    surveyPDF.save();

html is being rendered, and set the values as image below

![html](https://user-images.githubusercontent.com/4762619/77690804-a56c6f00-6f82-11ea-826b-7f4c68db9c37.PNG)

but the pdf is not being set the values and the widgets is distorted, as image just below

![pdf](https://user-images.githubusercontent.com/4762619/77690806-a69d9c00-6f82-11ea-8e97-087ca0f1dcb2.PNG)

**Comment by gologames** [comment]
Hello,

Sorry for late response. If you are using SurveyAngular, then there is known issue with SurveyPDF rendering (missing answers too) in Angular app. More details about this problem and [workaround here](https://github.com/surveyjs/survey-pdf/issues/4)

Otherwise could you share us a work sample with the issue? So we can investigate it
 
Thanks, Alex
SurveyJS Team

**Comment by gustavo-campos** [comment]
PDF search is not rendering the signaturepad widget. 
I'm in the latest version of angular at 1.5.18.

**Comment by gustavo-campos** [comment]
> Hello,
> 
> Sorry for late response. If you are using SurveyAngular, then there is known issue with SurveyPDF rendering (missing answers too) in Angular app. More details about this problem and [workaround here](https://github.com/surveyjs/survey-pdf/issues/4)
> 
> Otherwise could you share us a work sample with the issue? So we can investigate it
> 
> Thanks, Alex
> SurveyJS Team

PDF search is not rendering the signaturepad widget. 
I'm in the latest version of angular at 1.5.18.

**Comment by gologames** [comment]
Hello,

We can't reproduce issue on our side. [Export PDF with custom widgets example](https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-customwidgets&platform=jQuery&theme=modern#content-result-pdf-id) on SurveyAngular works fine for me (complete survey and press Save to PDF button on the top). Also I added custom widgets to PDF export of our S[urveyJS Angular App Quickstart repository](https://github.com/surveyjs/surveyjs_angular_cli). You can clone it and modify as you need

Thanks, Alex
SurveyJS Team
